import {
  Airplane,
  ArrowBendDownRight,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsOutSimple,
  AppleLogo,
  At,
  Bell,
  Brain,
  CalendarBlank,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartLine,
  ChatCircle,
  Check,
  CircleDashed,
  CircleNotch,
  Copy,
  DotsSixVertical,
  DotsThree,
  FolderSimple,
  Gauge,
  Gear,
  GithubLogo,
  Globe,
  Keyboard,
  List,
  ListChecks,
  MagnifyingGlass,
  Microphone,
  Moon,
  PaintBrush,
  Paperclip,
  PencilSimple,
  Plugs,
  Plus,
  Prohibit,
  SlidersHorizontal,
  Smiley,
  Sparkle,
  Star,
  Sun,
  TextAlignLeft,
  ThumbsDown,
  ThumbsUp,
  Trash,
  WarningCircle,
  X,
} from "@phosphor-icons/react";
import type { IconGlyph } from "./types";
import type { IconName } from "./names";

/** Phosphor's answer for every name in the Oreo vocabulary. */
export const phosphorGlyphs: Record<IconName, IconGlyph> = {
  "align-left": TextAlignLeft,
  "apple-logo": AppleLogo,
  "arrow-down": ArrowDown,
  "arrow-out": ArrowUpRight,
  "arrow-up": ArrowUp,
  at: At,
  bell: Bell,
  brain: Brain,
  calendar: CalendarBlank,
  camera: Camera,
  "chart-line": ChartLine,
  chat: ChatCircle,
  check: Check,
  "chevron-down": CaretDown,
  "chevron-left": CaretLeft,
  "chevron-right": CaretRight,
  "circle-dashed": CircleDashed,
  copy: Copy,
  "corner-down-right": ArrowBendDownRight,
  ellipsis: DotsThree,
  expand: ArrowsOutSimple,
  folder: FolderSimple,
  gauge: Gauge,
  gear: Gear,
  "github-logo": GithubLogo,
  globe: Globe,
  "grip-vertical": DotsSixVertical,
  keyboard: Keyboard,
  list: List,
  "list-checks": ListChecks,
  mic: Microphone,
  moon: Moon,
  paintbrush: PaintBrush,
  paperclip: Paperclip,
  pencil: PencilSimple,
  plane: Airplane,
  plug: Plugs,
  plus: Plus,
  prohibit: Prohibit,
  refresh: ArrowsClockwise,
  reset: ArrowCounterClockwise,
  search: MagnifyingGlass,
  sliders: SlidersHorizontal,
  smiley: Smiley,
  sparkle: Sparkle,
  spinner: CircleNotch,
  star: Star,
  sun: Sun,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  trash: Trash,
  "warning-circle": WarningCircle,
  x: X,
};
