import {
  AlignLeft,
  ArrowDown,
  ArrowUp,
  AtSign,
  Ban,
  Bell,
  Brain,
  Calendar,
  Camera,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleDashed,
  Copy,
  CornerDownRight,
  Ellipsis,
  Folder,
  Globe,
  GripVertical,
  ListChecks,
  LoaderCircle,
  Maximize2,
  MessageCircle,
  Mic,
  Moon,
  Paintbrush,
  Paperclip,
  Pencil,
  Plane,
  Plug,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  X,
} from "lucide-react";
// Lucide dropped brand marks, so these two keep borrowing Phosphor's. Swap them
// for local SVG assets (see `keyword-tag/assets`) if the Phosphor dependency
// ever needs to go away entirely.
import { AppleLogo, GithubLogo } from "@phosphor-icons/react";
import type { IconGlyph } from "./types";
import type { IconName } from "./names";

/** Lucide's answer for every name in the Oreo vocabulary. */
export const lucideGlyphs: Record<IconName, IconGlyph> = {
  "align-left": AlignLeft,
  "apple-logo": AppleLogo,
  "arrow-down": ArrowDown,
  "arrow-up": ArrowUp,
  at: AtSign,
  bell: Bell,
  brain: Brain,
  calendar: Calendar,
  camera: Camera,
  "chart-line": ChartLine,
  chat: MessageCircle,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-dashed": CircleDashed,
  copy: Copy,
  "corner-down-right": CornerDownRight,
  ellipsis: Ellipsis,
  expand: Maximize2,
  folder: Folder,
  "github-logo": GithubLogo,
  globe: Globe,
  "grip-vertical": GripVertical,
  "list-checks": ListChecks,
  mic: Mic,
  moon: Moon,
  paintbrush: Paintbrush,
  paperclip: Paperclip,
  pencil: Pencil,
  plane: Plane,
  plug: Plug,
  plus: Plus,
  prohibit: Ban,
  refresh: RefreshCw,
  reset: RotateCcw,
  search: Search,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  spinner: LoaderCircle,
  star: Star,
  sun: Sun,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  trash: Trash2,
  "warning-circle": CircleAlert,
  x: X,
};
